services:
  backend:
    build: ./backend
    container_name: restorex-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - D:/Backups/PostgreSQL:/backups/databases
      - ./logs:/app/logs
      - ./data:/app/data    # Encryption key stored here
    networks:
      - restorex-net

  frontend:
    build: ./frontend
    container_name: restorex-ui
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - restorex-net

networks:
  restorex-net:
    driver: bridge
